<form action="" method="get">
<div for="drop dwon" style="margin-top:50px;">
<lable for="role"><b><?php echo $this->locale->_('Select Language') ?></b></label>   
<select name="locale" onchange="this.form.submit()">
<option value="sl" name="sl">Select</option>
<option value="en" name="en">English</option>
<option value="hn" name="hn">Hindi</option>
<option value="fr" name="fr">French</option>
<option value="ur" name="ur">Urdu</option>
<input type="hidden" name="bearer" value="<?php echo $_GET['bearer']?>">
</select>
</div>
</form>
<?php

echo "<h1 style='text-align:center;'>". $this->locale->_('Product List')."</h1>";

echo PHP_EOL;

echo $this->tag->linkTo([
    'product',
    // 'Add Product! '
    $this->locale->_('Add Product !' )

]);
echo $this->tag->linkTo([
    'order',
    $this->locale->_('Add Order !' )
]);
?>


<?php
if ($products->count() > 0 )
 {
    ?>
   
    
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th><?php echo  $this->locale->_('Product ID') ?></th>
            <th><?php echo $this->locale->_('Name') ?></th>
            <th><?php echo $this->locale->_('Description') ?></th>
            <th><?php echo $this->locale->_('Tag') ?></th>
            <th><?php echo $this->locale->_('Price') ?></th>
            <th><?php echo $this->locale->_('Stock') ?></th>
            <th><?php echo $this->locale->_('Action') ?></th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3"><?php echo $this->locale->_('Total Products : ')?><?php echo $products->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($products as $product) 
        {
?>
            
            
            <tr>
                <td><?php echo $product->productid; ?></td>
                <td><?php echo $this->locale->_($product->name); ?></td>
                <td><?php echo $product->description; ?></td>
                <td><?php echo $product->tags; ?></td>
                <td><?php echo $product->price; ?></td>
                <td><?php echo $product->stock; ?></td>
                <td><?php //echo $this->tag->linkTo([
                        //'edit/edit/'.$user->id,
                        //'Edit', 'class' => 'btn btn-primary' ]);?>
                    <?php echo $this->tag->linkTo([
                            'index/delete/'.$product->productid,
                            'Delete', 'class' => 'btn btn-danger' ]);?></td>

            </tr>
        <?php

}   }  
echo $this->tag->linkTo([
    'index2',
    $this->locale->_('Show Order !' ) 
]); 
echo $this->tag->linkTo([
    'settings',
    $this->locale->_('Settings !' )
]);    ?>
        </tbody>
    </table>
