<h2>Sign Form AWT</h2>

<?php echo $this->tag->form("acl/createtoken"); ?>

    <p>
 <?php     
echo $this->tag->select(
    [
        "dropdown",
        Roles::find(),
        "using" => ["roles","roles"],
    ]
);
?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>
    </p>

    <p>
        <?php echo $this->tag->submitButton(['class'=>'btn btn-primary',"Register"]); ?>
     
    </p>

</form>